name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.9.0]

    steps:
    - uses: actions/checkout@v1
    - name: Check cache
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: npm-${{ hashFiles('**/package-lock.json') }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: npm install, build, and test
      run: |
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
